config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/about' => "homes#about", as: "about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user

  def get_image
    if profile_image.attached?
      image
    else
      'no_image.jpg'
    end
  end
   validates :title, presence: true
   validates :body, length: {maximum: 200}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  has_one_attached :profile_image

   def get_profile_image(width, height)
    unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
   end
  validates :name, presence: true,  length: { in: 2..20}, uniqueness: true
  validates :introduction,  length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def autheniticate_user
  if current_user==nil
     redirect_to ("/users/sign_in")
  end
 end
 before_action :configure_permitted_parameters, if: :devise_controller?
      def after_sign_in_path_for(resource)
       user_path(current_user.id)
      end
        def after_sign_up_path_for(resource)
            user_path(current_user.id)
        end



  def after_sign_out_path_for(resource)
    root_path
  end

 protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!
 before_action :correct_user, only: [:edit, :update]

 def new
   @book= Book.new
 end

 def create
  @books = Book.new(book_params)
  @book= Book.all
  @user=current_user
  @books.user_id = current_user.id
  if @books.save
   flash[:notice] = "You have created book successfully."
    redirect_to book_path(@books.id)
  else
   render :index
  end
 end

  def index
  @book= Book.all
  @books= Book.new
  @user=current_user
  end

  def show
   @book=Book.find(params[:id])
   @books=Book.new
   @user=@book.user
  end

  def edit
    @book = Book.find(params[:id])
  if @book.user_id ==current_user.id
   render :edit
  else
    redirect_to books_path
  end
  end

  def update
   @book=Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] ="You have updated book successfully."
    redirect_to book_path(@book.id)
   else
    render :edit
   end
  end

  def destroy
   book= Book.find(params[:id])
   book.destroy
   redirect_to '/books'
  end
end

  private

  def book_params
    params.require(:book).permit(:title, :body, :profile_image)
  end

  def correct_user
   @book=Book.find(params[:id])
   @user= @book.user
   redirect_to books_path unless @user==current_user
  end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :autheniticate_user, {only: [:edit, :update,:index,:show]}

  def index
    @users=User.all
    @books=current_user
  end

  def show
    @user=User.find(params[:id])
    @books = @user.books
    @book=Book.new
  end

  def edit
   @user=User.find(params[:id])
   if @user.id ==current_user.id
     render :edit
   else
      redirect_to user_path(current_user.id)
   end
  end

  def update
   @user=User.find(params[:id])
   if @user.update(user_params)
       flash[:notice] ="You have updated user successfully."
   redirect_to user_path(@user.id)
   else
     render "edit"
   end
  end


    private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div>
 <h3>User Info</h3>
  <%= image_tag books.get_profile_image(100,100) %>
  <table>
   <tr>
    <th>Name</th><th><%= books.name%></th>
   </tr>
   <tr>
    <th>introduction</th>
    <th><%= books.introduction %></th>
   </tr>
   <tr>
    <% if books==current_user %>
    <th><a class="btn btn-block btn-outline-secondary " href="/users/<%= current_user.id %>/edit"><i class="fas fa-user-cog"></i></a>
     </th>
    <% else %>
    <th><a class="btn btn-block btn-outline-secondary"  href="/users/<%= books.id %>/edit"><i class="fas fa-user-cog"></i></i></a>
      <% end %>
     </th>
   </tr>
  </table>
 </div>

app/views/books/edit.html.erb
 <div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5  mx-auto">
   <h1>Editing Book</h1>
   <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved:
    <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
    </ul>
    <% end %>

    <%= form_with model: @book do |f| %>
    <div class="form-group">
    <h4>Title</h4><br>
    <%= f.text_field :title %>
    </div>
    <div class="form-group">
    <h4>Opinion</h4><br>
    <%= f.text_area :body %>
    </div>
    <div class="form-group">
     <input type="submit" class="btn btn-success" value="Update Book">
    </div>
    <% end %>
   <span><%= link_to'Show', book_path(@book.id) %></span>
   |
   <%= link_to'Back', books_path %>
   </div>
  </div>
 </div>
 <div class="container">
  <div class="row">
   <div class="mx-auto">
   <footer>CopyRight Infratop.inc</footer>
   </div>
  </div>
 </div>

app/views/books/index.html.erb
<main>
 <div class="container">
  <%= flash[:notice] %>
    <% if @books.errors.any? %>
    <h3><%= @books.errors.count %>errors prohibited this obj from being saved:</h3>
     <ul>
      <% @books.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
     </ul>
    <% end %>
  <div class="row">

   <div class="col-md-3">
    <%= render 'list', books: @user %>

    <h3>New book</h3>

    <%= form_with model: @books do |f| %>

    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>opinion</h4>
      <%= f.text_area :body %>
    <input class= "btn btn-success" type="submit" value="Create Book">
    <% end %>
   </div>
   <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
    <table class="table table-striped">
     <thead>
      <tr class="border-top border-bottom">
       <th>Title</th>
       <th>Opinion</th>
      </tr>
     </thead>
     <tbody>
     <% @book.each do |book| %>
      <tr>
      <th><%= link_to user_path(book.user.id) do %>
       <%= image_tag book.user.get_profile_image(100,100) %>
       <% end %>
      </th>
      <th><%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %>
      </th>
      <th><%= book.body %></th>
      </tr>
     <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>
</main>
 <div class="container">
  <div class="row">
   <div class="mx-auto">
   <footer>CopyRight Infratop.inc</footer>
   </div>
  </div>
 </div>

app/views/books/new.html.erb
<h1>New Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <%= form_with model: @book do |f| %>

    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit 'create book' %>
  <% end %>

<%= render 'list', books: @books %>

app/views/books/show.html.erb
<%= flash[:notice] %>
<main>
 <div class="container">
  <div class="row">
   <div class="col-md-3">
    <%= render 'list', books: @user %>
    <h3>New book</h3>
    <% if @books.errors.any? %>
    <%= @books.errors.count %>errors prohibited this obj from being saved:
    <ul>
    <% @books.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
    <% end %>
    <%= form_with model: @books,  method: :post do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>opinion</h4>
    <%= f.text_area :body %>
    <input class= "btn btn-success" type="submit" value="Create Book">
    <% end %>
   </div>
   <div class="col-md-8 offset-md-1">
   <table class="table table-striped">
    <thead>
     <h2>Book detail</h2>
    </thead>
    <tbody>
     <tr>
      <td><%= link_to user_path(@book.user) do %>
          <%= image_tag @book.user.get_profile_image(100,100) %>
        <br><%= @book.user.name%>
          <% end %>
      </td>
      <td><%= link_to @book.title,book_path(@book.id) %></td>
      <td><%= @book.body %></td>
       <% if @book.user_id == current_user.id %>
       <td><a class=" btn btn-success btn-block" href="/books/<%=@book.id %>/edit">Edit</a></td>
       <td><a class=" btn btn-danger btn-block" data-method="delete" href="/books/<%=@book.id %>">Destroy</a></td>
       <% end %>
     </tr>
    </tbody>
   </table>
   </div>
  </div>
 </div>
</main>
 <div class="container">
  <div class="row">
   <div class="mx-auto">
   <footer>CopyRight Infratop.inc</footer>
   </div>
  </div>
 </div>

app/views/homes/about.html.erb
<div class= " mx-auto p-3 text-center">
<h1>Welcome to <i class="fas fa-book"></i> Bookers!</h1>
<p class= "pt-5">CopyRight Infratop.inc</p>

app/views/homes/top.html.erb
 <%= flash[:notice] %>
  <div class="pt-2 mx-auto " >
  <h1 >welcome to<i class="fas fa-book"></i><span class="font-weight-bold ">Bookers!!</span></h1>

  <p class= "pb-2">In <i class="fas fa-book"></i><span class="font-weight-bold">Bookers</span><br>

   you can share and exchange your opinions , inpressions , and emotions<br>

   about various books!</p>


   <a class="btn btn-info btn-sm btn-block mb-3" href="/users/sign_in">Log in</a>
   <a class="btn bg-success text-light btn-sm btn-block " href="/users/sign_up">Sign up</a>
  </div>
   <div class="container">
  <div class="row">
   <div class="mx-auto">
   <footer>CopyRight Infratop.inc</footer>
   </div>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--<script src="https://kit.fontawesome.com/8391bc956b.js" crossorigin="anonymous"></script>-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light text-light bg-dark">
        <div class="container">
           <a class= "h4 text-light text-decoration-none" href="/" >Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
             <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
            </li>
             <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> Users
             <% end %>
             </li>
             <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light ' do %>
              <i class="fas fa-book-open"></i> Books
              <% end %>
             </li>
             <li class="nav-item">
              <%= link_to destroy_user_session_path, class: 'nav-link text-light' do%>
              <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
             </li>
             <% else %>
              <li class="nav-item ">
              <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
             </li>
             <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light ' do %>
              <i class="fas fa-link"></i> About
              <% end %>
             </li>
             <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
              <% end %>
             </li>
             <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
             </li>
             <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
   
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<main>
 <div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5  mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user do |f| %>
    <div class="form-group">
     <label for="inputName">Name</label><br>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%>
    </div>
    <div class="form-group">
     <label for="inputImage">Image</label><br>
      <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
    </div>
    <div class="form-group">
     <label for="inputintroduction">introduction</label><br>
      <%= f.text_area :introduction, autofocus: true, placeholder:"introduction"%>
    </div>
    <div class="form-group">
     <input type="submit" class="btn btn-secondary" value="Update User">
    </div>
    <% end %>
    </div>
  </div>
 </div>
</main>
 <div class="container">
  <div class="row">
   <div class="mx-auto">
   <footer>CopyRight Infratop.inc</footer>
   </div>
  </div>
 </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">

  <div class="row">
   <div class="col-md-3">
    <%= render 'books/list', books: @books %>

    <h3>New book</h3>
      <% if Book.new.errors.any? %>
      <%= Book.new.errors.count %>errors prohibited this obj from being saved:
      <ul>
       <% Book.new.errors.full_messages.each do |message| %>
       <li><%= message %></li>
       <% end %>
      </ul>
      <% end %>

      <%= form_with model: Book.new do |f| %>
      <div class="form-group">
       <label>Title</label><br>
       <input class="form-control book-title" type="text" name="book[title]" id="book_title">
      </div>
      <div class="form-group">
       <label>Opinion</label><br>
      <%= f.text_area :body %><br>
      </div>
      <div class="form-group">
       <input class= "btn btn-success" type="submit" value="Create Book">
      <% end %>
      </div>
   </div>

   <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
    <table class="table table-striped">
     <thead>
      <tr class="border-top border-bottom">
       <th>image</th>
       <th>name</th>
      </tr>
     </thead>
     <tbody>
      <% @users.each do |user| %>
      <tr class="border-top border-bottom">
       <td><%= image_tag user.get_profile_image(100,100) %></td>
       <td><%= user.name %></td>
       <th><%= link_to"Show", user_path(user.id)%></th>
      </tr>
      <% end %>
     </tbody>
    </table>
   </div>
  </div>
</div>
 <div class="container">
  <div class="row">
   <div class="mx-auto">
   <footer>CopyRight Infratop.inc</footer>
   </div>
  </div>
 </div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<main>
<div class="container">
 <div class="row">
  <div class="col-md-3">
    <%= render 'books/list', books: @user %>
    <h3>New book</h3>
     <% if Book.new.errors.any? %>
     <%= Book.new.errors.count %>errors prohibited this obj from being saved:
     <ul>
     <% Book.new.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
     </ul>
     <% end %>
     <%= form_with model: Book.new do |f| %>
      <label>Title</label><br>
      <input class="form-control book-title" type="text" name="book[title]" id="book_title">
     <label>Opinion</label><br>
      <%= f.text_area :body %><br>
     <input class= "btn btn-success" type="submit" value="Create Book">
     <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
  <h1>Books</h1>
  <table class="table table-striped">
   <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
    </tr>
   </thead>
   <% @books.each do |book| %>
   <tbody>
    <tr>
     <td><%= link_to user_path(book.user.id) do %>
       <%= image_tag book.user.get_profile_image(100,100) %>
       <% end %>
     </td>
     <td><%= link_to book_path(book.id) do %>
       <%= book.title %>
       <% end %>
     </td>
     <td><%= book.body %></td>
    </tr>
   </tbody>
   <% end %>
  </table>
  </div>
 </div>
</div>
</main>
 <div class="container">
  <div class="row">
   <div class="mx-auto">
   <footer>CopyRight Infratop.inc</footer>
   </div>
  </div>
 </div>